### ISSUE TITLE
cannot change font size 

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#57]
![image](https://user-images.githubusercontent.com/16418270/159171577-06ddfffa-03b4-4dd5-8d01-abbeb914e199.png)

the configuration didn't have any effect

**Comment by debanjandhar12** [comment]
Try:
```css
.text {
font-size: 20px !important;
}
```
